var namespacedwmipc =
[
    [ "Client", "structdwmipc_1_1Client.html", "structdwmipc_1_1Client" ],
    [ "ClientFocusChangeEvent", "structdwmipc_1_1ClientFocusChangeEvent.html", "structdwmipc_1_1ClientFocusChangeEvent" ],
    [ "Connection", "classdwmipc_1_1Connection.html", "classdwmipc_1_1Connection" ],
    [ "EOFError", "classdwmipc_1_1EOFError.html", "classdwmipc_1_1EOFError" ],
    [ "ErrnoError", "classdwmipc_1_1ErrnoError.html", "classdwmipc_1_1ErrnoError" ],
    [ "FocusedTitleChangeEvent", "structdwmipc_1_1FocusedTitleChangeEvent.html", "structdwmipc_1_1FocusedTitleChangeEvent" ],
    [ "Geometry", "structdwmipc_1_1Geometry.html", "structdwmipc_1_1Geometry" ],
    [ "HeaderError", "classdwmipc_1_1HeaderError.html", "classdwmipc_1_1HeaderError" ],
    [ "InvalidOperationError", "classdwmipc_1_1InvalidOperationError.html", "classdwmipc_1_1InvalidOperationError" ],
    [ "IPCError", "classdwmipc_1_1IPCError.html", null ],
    [ "Layout", "structdwmipc_1_1Layout.html", "structdwmipc_1_1Layout" ],
    [ "LayoutChangeEvent", "structdwmipc_1_1LayoutChangeEvent.html", "structdwmipc_1_1LayoutChangeEvent" ],
    [ "Monitor", "structdwmipc_1_1Monitor.html", "structdwmipc_1_1Monitor" ],
    [ "MonitorFocusChangeEvent", "structdwmipc_1_1MonitorFocusChangeEvent.html", "structdwmipc_1_1MonitorFocusChangeEvent" ],
    [ "NoMsgError", "classdwmipc_1_1NoMsgError.html", "classdwmipc_1_1NoMsgError" ],
    [ "Packet", "classdwmipc_1_1Packet.html", "classdwmipc_1_1Packet" ],
    [ "ReplyError", "classdwmipc_1_1ReplyError.html", "classdwmipc_1_1ReplyError" ],
    [ "ResultFailureError", "classdwmipc_1_1ResultFailureError.html", "classdwmipc_1_1ResultFailureError" ],
    [ "Size", "structdwmipc_1_1Size.html", "structdwmipc_1_1Size" ],
    [ "SocketClosedError", "classdwmipc_1_1SocketClosedError.html", "classdwmipc_1_1SocketClosedError" ],
    [ "Tag", "structdwmipc_1_1Tag.html", "structdwmipc_1_1Tag" ],
    [ "TagChangeEvent", "structdwmipc_1_1TagChangeEvent.html", "structdwmipc_1_1TagChangeEvent" ],
    [ "TagState", "structdwmipc_1_1TagState.html", "structdwmipc_1_1TagState" ]
];